### ISSUE TITLE
Is your F4 a F401CCU6? How much Mhz crystal is he? Your firmware usb doesn't work

### ISSUE THREAD

**Issue by hankecnc** [Paciente8159/uCNC#171]
The program seems to be running? The PC13 light is on, but it is an unknown USB device. It is certain that there is no problem with my usb virtual serial port (I have tried grblhal's f401 firmware and he has no problem)

**Comment by hankecnc** [comment]
![IMG_20220422_160712](https://user-images.githubusercontent.com/69781416/164646001-20589bde-4fb6-4dc0-8fad-873f520379ca.jpg)

**Comment by hankecnc** [comment]
I don't have the f103c8t6 board to test anymore

**Comment by Paciente8159** [comment]
How did you compiled it?
Arduino IDE, makefile or PlatformIO?

**Comment by Paciente8159** [comment]
In about an hour I'll be able to test it and let you know. I think it is 25Mhz.

**Comment by Paciente8159** [comment]
I've just uploaded the bin that is precompiled in github and it's working. Even without Pin B5 grounded.
I used st-link to upload the firmware. What did you use?
Here is a pic. I confirm it's a 401cdu6 at 25mhz
![IMG_20220422_165320](https://user-images.githubusercontent.com/12116536/164750962-6e57a1bc-6347-46ad-8923-9303f2083893.jpg)

**Comment by Paciente8159** [comment]
Also tried with STM32CubeProgrammer in DFU mode and again all worked.

**Comment by hankecnc** [comment]
The led of PC13 is only on, not flashing, I try to burn the grblhal version again, his usb virtual serial port works fine, you have noticed that your chip is CDU6 instead of CCU6, I don't know what will be the difference, just flash capacity
![ccc](https://user-images.githubusercontent.com/69781416/164816301-af363371-1d03-4b4e-99ea-e321ee31502f.jpg)
?

**Comment by hankecnc** [comment]
![ccc](https://user-images.githubusercontent.com/69781416/164816348-0a8f5939-d8ae-4c06-9099-745177eded35.jpg)

**Comment by hankecnc** [comment]
I bought a f103c8t6 today, it's on the way, it will arrive the day after tomorrow

**Comment by Paciente8159** [comment]
what did you use to upload the firmware?

**Comment by hankecnc** [comment]
> what did you use to upload the firmware? If the led is not blinking that is an indication that the firmware is not running somehow.

Tried both with usb dfu and serial port with STM32CubeProgrammer

**Comment by hankecnc** [comment]
> what did you use to upload the firmware? If the led is not blinking that is an indication that the firmware is not running somehow.

I have a little knowledge of microcontrollers, the PC13 LED is on means it is indeed running

**Comment by hankecnc** [comment]
> what did you use to upload the firmware? If the led is not blinking that is an indication that the firmware is not running somehow.

In your program, does the PC13 LED light flash as long as it is plugged in without any communication?

**Comment by Paciente8159** [comment]
The PC13 blinks because there is an internal function that runs every millisecond.

Can you try the alternative method via Arduino IDE?
![arduino-ide](https://user-images.githubusercontent.com/12116536/164887141-26698c84-0457-4029-ad16-1bbdceb75457.png)
![arduino-ide2](https://user-images.githubusercontent.com/12116536/164887142-2ed0c4c1-808a-449e-9d6a-8435b71ced85.png)

**Comment by Paciente8159** [comment]
If you don't have the STM32duino installed please read the [wiki tutorial](https://github.com/Paciente8159/uCNC/wiki/STM32Fx:-Compiling#method-two---arduino-ide-easiest)

**Comment by hankecnc** [comment]
> If you don't have the STM32duino installed for Arduino IDE please read the [wiki tutorial](https://github.com/Paciente8159/uCNC/wiki/STM32Fx:-Compiling#method-two---arduino-ide-easiest)

Thanks, I will try again when my C8T6 arrives

**Comment by hankecnc** [comment]
> How did you compiled it? Arduino IDE, makefile or PlatformIO or used the precompiled file? I don't have my board with me right now but I will confirm it in couple of hours.
> 
> By the way... have you tried grounding PIN B5? That's the Emergency stop. If left unconnected it will lock the firmware for safety reasons. That can be modified via config file.

Hello, after experiments, the firmware burning of the F103c8t6 version I purchased works normally

**Comment by hankecnc** [comment]
Depending on how you keep updating it, I'll try his

**Comment by hankecnc** [comment]
I'll try him on my machine and see how he performs

**Comment by Paciente8159** [comment]
> I'll try him on my machine and see how he performs

Thanks let me know if you find something off and I'll try to fix it ASAP.
