### ISSUE TITLE
How to configure mega2560 and tmc 2209 driver

### ISSUE THREAD

**Issue by wrenchonline** [Paciente8159/uCNC#220]
**Describe the bug**
amazing project.But I'm a newbie,I don't know how to make it work.

**What is your hardware**
Describe your hardware:
1. arduino mega2560 （this is not mks_gen_l_v1）
    tmc2209 x 3
    
4. If this is a custom compilation tell us what configurations you changed
   platformio.ini 
        [env:mks_gen_l_v1]
        platform = atmelavr
        board = megaatmega2560
        framework = arduino
        build_src_filter = +<*>-<src/tinyusb>
        build_flags = -D BOARD=BOARD_MKS_GEN_L_V1 -ffunction-sections -fdata-sections -mcall-prologues -mrelax -flto -fno-fat-lto-objects -fno-tree-scev-cprop -Wl,--gc-sections -Wl,--relax
        extra_scripts = avr_compiler.py
cnc_hal_config.h
      #define STEPPER0_HAS_TMC
      .....
     #define STEPPER0_DRIVER_TYPE 2209

**Screenshots**

**Additional context**
    In fact I don't know the pins tested in the mega2560（this is This is the official board）.

**Comment by Paciente8159** [comment]
Thanks. Although Tmc2209 was not tested it should work like the Tmc2208.
The pinout is tha same Marlin for the RAMPS or the the MKS Gen L.
Any problem let me know.

**Comment by wrenchonline** [comment]
> Thanks. Although Tmc2209 was not tested it should work like the Tmc2208. The pinout is tha same Marlin for the RAMPS or the the MKS Gen L. Any problem let me know.
> 
> **EDIT**: here is an [instructable](https://www.google.com/amp/s/www.instructables.com/UART-This-Serial-Control-of-Stepper-Motors-With-th/%3famp_page=true). The connections and cables should match this setup.

After my day of research, I was finally able to drive the motor. But I found that running the command
`$4 = 0` 
the motor step_en_pin has low level，it didn't disabled.

**Comment by Paciente8159** [comment]
Thanks. I'll look into that and report soon

**Comment by Paciente8159** [comment]
Just one more note. Tmc initialization happens only on power up. Tmc drivers only accept commands when powered up. If the board is powered up via USB cable initial configuration will be sent but the tmc drivers will not get configure.
Power up must happen from the PSU. I will review this limitation soon.

**Comment by Paciente8159** [comment]
I've tested $4 setting and all is working as expected.
As explained after changing the $4 value you need to either do a soft reset or send and unlock command ($X) and the step enable pins will update.

I'll build the M17/M18 module and add it to the modules repository. It's an easy module to build so I'll be able to build it and upload it today. I'll let you know when it's done.

**Comment by Paciente8159** [comment]
I've created and uploaded the [M17-M18 module](https://github.com/Paciente8159/uCNC-modules/tree/master/M17-M18). You can include it in the project like explained in the instructions.
