### ISSUE TITLE
TMC2209 set stepper motor current failure

### ISSUE THREAD

**Issue by wrenchonline** [Paciente8159/uCNC#223]
**Describe the bug**

**What is your hardware**
Describe your hardware:
1. What's your board
    Arduino Mage2560 R3
    TMC2209
3. Paste your "Grbl/µCNC settings"
    Input  M906
`[STEPPER CURRENT:X30.596,Y30.596,Z-1.000,A-1.000,B-1.000,C-1.000,I-1.000,J-1.000]`
        Input   M906 X800 Y800   \
                   ok
                   M906
`[STEPPER CURRENT:X30.596,Y30.596,Z-1.000,A-1.000,B-1.000,C-1.000,I-1.000,J-1.000]`

5. If this is a custom compilation tell us what configurations you changed
    It seems that setting the current does nothing, I suspect it may be that I don't understand the tmc driver.

**Additional context**

**Comment by Paciente8159** [comment]
Thanks for the report. I'll try to check it tonight.

**Comment by Paciente8159** [comment]
I'm getting similar results on the TMC2208. I'll investigate. Have you tried sending motion commands. Do the motors stall or loose steps?

**Comment by wrenchonline** [comment]
> 我在[tmc-drivers-fix](https://github.com/Paciente8159/uCNC/tree/tmc-drivers-fix)分支有一个提议的补丁。 我还没有测试过这个。我只能明天测试它。
> 
> 该分支尝试解决以下问题：
> 
> * 修复了未正确加载的 M914 命令和 TMC2130 的正确配置
> * 添加了 Marlin M913 命令
> * 通过 M 命令修改的 TMC 设置在软复位后不会丢失。这些仍然没有存储在 eeprom 中，因此硬重置会将它们恢复为默认值。
> * 现在所有 TMC M 命令都应该报告正确的值
> 
> > 实际设置电流也不行。我的可调电源用的是80mA。设置成功后，我把可调电压关掉再开机，电源是800MA，但是加速不大
> 
> 我不明白这个问题。你是不是电机转得太慢了？ 你能给我发一份你的设置输出`$$`和你的配置信息`$I`吗？

yeah，that right. this is my configuration:
$$
Sent 3 bytes
-> $0=33.333
$1=0
$2=0
$3=0
$4=0
$5=0
$6=0
$7=0
$10=1
$11=0.200
$12=0.002
$13=0
$20=0
$21=0
$22=0
$23=0
$24=10.000
$25=50.000
$26=250
$27=2.000
$30=1000.000
$31=0.000
$32=0
$80=1
$81=0.000
$100=40.000
$101=40.000
$102=200.000
$110=500.000
$111=500.000
$112=500.000
$120=100.000
$121=100.000
$122=10.000
$130=200.000
$131=200.000
$132=200.000

$I
Sent 3 bytes
-> [VER: uCNC 1.4.6 - MKS GEN L V1]
[OPT:C3,DSS3_500,DC,XC,30,128]
ok

M350
Sent 5 bytes
-> [MICROSTEPS:X8.000,Y8.000,Z-1.000,A-1.000,B-1.000,C-1.000,I-1.000,J-1.000]

**Comment by wrenchonline** [comment]
I think I solved the problem.run the command:
`$110=1000  $111=1000`

**Comment by Paciente8159** [comment]
What kind of linear system are you using? I'm assuming based on your configs the X and Y axis are using gt2 belt with a 20teeth timing pulley and a 1.8º/step motor.
What GUI/PC app are you using? 
When you send the G0X50Y50 how does it move in the GUI? At normal speed or slow?
Does the board freezes? 

Tomorrow I Will test your settings on my board to see if I can replicate the problem. 

I did a quick test on the new branch and there are issues that I still have to solve with the new code for the Tmc driver. I'll repick that task tomorrow.

**Comment by wrenchonline** [comment]
This shouldn't be an freezes issue, I'm just testing a single instruction.I use Candle GUI program And this is my gcode:
%
(Header)
(Generated by gcodetools from Inkscape.)
(Using default header. To add your own header create file "header" in the output dir.)
M3
(Header end.)
G21 (All units in mm)

(Start cutting path id: path7517)
(Change tool to Graffiti)
(Add G00 here to change sprayer if needed)
G00 Z5.000000
G00 X142.673750 Y36.041237
M42 P24 S170
G01 Z-1.000000 F100.0(Penetrate)
G01 X140.342110 Y36.041237 Z-1.000000 F400.000000
G01 X140.342110 Y43.929127 Z-1.000000
G03 X140.312358 Y44.882119 Z-1.000000 I-15.277773 J-0.000000
G03 X140.230490 Y45.715065 Z-1.000000 I-11.749558 J-0.734340
G03 X140.050282 Y46.533589 Z-1.000000 I-4.887294 J-0.646900
G03 X139.821210 Y47.029713 Z-1.000000 I-2.000975 J-0.622949
G03 X139.446249 Y47.476331 Z-1.000000 I-1.558264 J-0.927541
G03 X138.928240 Y47.798659 Z-1.000000 I-1.295230 J-1.504138
G03 X138.328686 Y47.981058 Z-1.000000 I-1.026344 J-2.297056
G03 X137.415150 Y48.059108 Z-1.000000 I-0.913536 J-5.307229
G03 X136.483559 Y47.950658 Z-1.000000 I-0.000000 J-4.055438
G03 X135.418380 Y47.587819 Z-1.000000 I1.341070 J-5.681884
G03 X134.411087 Y47.058874 Z-1.000000 I3.996172 J-8.833671
G03 X133.421600 Y46.384791 Z-1.000000 I5.540959 J-9.196856
G01 X133.421600 Y36.041237 Z-1.000000
G01 X131.089960 Y36.041237 Z-1.000000
G01 X131.089960 Y55.339283 Z-1.000000
G01 X133.421600 Y55.339283 Z-1.000000
G01 X133.421600 Y48.356764 Z-1.000000
G02 X134.562510 Y49.181725 Z-1.000000 I6.767962 J-8.158593
G02 X135.678830 Y49.770631 Z-1.000000 I4.522059 J-7.219439
G02 X136.870977 Y50.152914 Z-1.000000 I2.482407 J-5.691371
G02 X138.072480 Y50.279127 Z-1.000000 I1.201503 J-5.655849
G02 X140.138427 Y49.885952 Z-1.000000 I0.000000 J-5.624370
G02 X141.495520 Y48.927272 Z-1.000000 I-1.289614 J-3.265439
G02 X142.317314 Y47.441887 Z-1.000000 I-3.047404 J-2.656010
G02 X142.673750 Y45.032936 Z-1.000000 I-7.962167 J-2.408951
G01 X142.673750 Y36.041237 Z-1.000000
G00 Z5.000000
M42 P24 S0
 
(End cutting path id: path7517)


(Start cutting path id: path7515)
(Change tool to Graffiti)
(Add G00 here to change sprayer if needed)
G00 Z5.000000
G00 X128.101000 Y36.909401
M42 P24 S170
 
G01 Z-1.000000 F100.0(Penetrate)
G02 X126.918109 Y36.395800 Z-1.000000 I-7.556579 J15.784836 F400.000000
G02 X125.880980 Y36.041237 Z-1.000000 I-4.604307 J11.773873
G02 X124.827373 Y35.812238 Z-1.000000 I-2.045485 J6.872840
G02 X123.660960 Y35.731178 Z-1.000000 I-1.166413 J8.351511
G02 X122.179816 Y35.847218 Z-1.000000 I-0.000000 J9.510724
G02 X120.907640 Y36.165260 Z-1.000000 I1.153900 J7.319023
G02 X119.731999 Y36.733504 Z-1.000000 I2.036590 J5.713773
G02 X118.762030 Y37.504713 Z-1.000000 I2.893032 J4.634220
G02 X117.983687 Y38.479198 Z-1.000000 I3.709162 J3.760673
G02 X117.360570 Y39.761940 Z-1.000000 I5.867320 J3.642883
G02 X117.003613 Y41.150710 Z-1.000000 I6.944122 J2.525116
G02 X116.864480 Y42.949342 Z-1.000000 I11.556300 J1.798632
G02 X117.403411 Y46.130516 Z-1.000000 I9.658305 J-0.000000
G02 X118.724830 Y48.282350 Z-1.000000 I5.585808 J-1.948536
G02 X120.824727 Y49.681122 Z-1.000000 I4.267071 J-4.130297
G02 X123.660960 Y50.217116 Z-1.000000 I2.836233 J-7.236025
G02 X124.839480 Y50.132920 Z-1.000000 I-0.000000 J-8.290170
G02 X125.992600 Y49.882252 Z-1.000000 I-1.175583 J-8.185519
G02 X127.126664 Y49.498314 Z-1.000000 I-3.804589 J-13.104731
G02 X128.101000 Y49.063698 Z-1.000000 I-3.921348 J-10.100458
G01 X128.101000 Y46.471608 Z-1.000000
G01 X127.976980 Y46.471608 Z-1.000000
G03 X126.864371 Y47.221743 Z-1.000000 I-6.012381 J-7.717445
G03 X125.769360 Y47.749049 Z-1.000000 I-4.019469 J-6.946278
G03 X124.620536 Y48.089538 Z-1.000000 I-2.491372 J-6.297665
G03 X123.561740 Y48.195534 Z-1.000000 I-1.058796 J-5.235155
G03 X121.747508 Y47.824502 Z-1.000000 I-0.000000 J-4.621033
G03 X120.423950 Y46.856080 Z-1.000000 I1.423008 J-3.333523
G03 X119.633353 Y45.399093 Z-1.000000 I2.972938 J-2.556182
G03 X119.282930 Y42.949342 Z-1.000000 I8.387703 J-2.449751
G03 X119.620914 Y40.565571 Z-1.000000 I8.575244 J-0.000000
G03 X120.399140 Y39.092213 Z-1.000000 I3.945433 J1.141764
G03 X121.703246 Y38.130099 Z-1.000000 I2.661320 J2.242422
G03 X123.561740 Y37.752760 Z-1.000000 I1.858494 J4.388115
G03 X124.263020 Y37.797913 Z-1.000000 I0.000000 J5.468383
G03 X125.000410 Y37.938795 Z-1.000000 I-0.800343 J6.189318
G03 X125.718336 Y38.161472 Z-1.000000 I-1.788715 J7.035598
G03 X126.315060 Y38.422487 Z-1.000000 I-1.882010 J5.115205
G03 X126.817048 Y38.694285 Z-1.000000 I-5.683239 J11.095942
G03 X127.270040 Y38.968190 Z-1.000000 I-5.318938 J9.308139
G03 X127.710874 Y39.273534 Z-1.000000 I-8.365419 J12.548297
G03 X127.976980 Y39.476686 Z-1.000000 I-3.432319 J4.771804
G01 X128.101000 Y39.476686 Z-1.000000
G01 X128.101000 Y36.909401 Z-1.000000
G00 Z5.000000
M42 P24 S0
 
(End cutting path id: path7515)


(Start cutting path id: path7513)
(Change tool to Graffiti)
(Add G00 here to change sprayer if needed)
G00 Z5.000000
G00 X113.367010 Y36.041237
M42 P24 S170
 
G01 Z-1.000000 F100.0(Penetrate)
G01 X111.035370 Y36.041237 Z-1.000000 F400.000000
G01 X111.035370 Y43.929127 Z-1.000000
G03 X111.005618 Y44.882119 Z-1.000000 I-15.277773 J0.000000
G03 X110.923750 Y45.715065 Z-1.000000 I-11.749558 J-0.734340
G03 X110.743550 Y46.533588 Z-1.000000 I-4.887154 J-0.646823
G03 X110.514480 Y47.029713 Z-1.000000 I-2.000925 J-0.622918
G03 X110.139519 Y47.476331 Z-1.000000 I-1.558264 J-0.927541
G03 X109.621510 Y47.798659 Z-1.000000 I-1.295230 J-1.504138
G03 X109.021956 Y47.981058 Z-1.000000 I-1.026344 J-2.297056
G03 X108.108420 Y48.059108 Z-1.000000 I-0.913536 J-5.307229
G03 X107.176829 Y47.950659 Z-1.000000 I-0.000000 J-4.055458
G03 X106.111640 Y47.587819 Z-1.000000 I1.341092 J-5.682005
G03 X105.104357 Y47.058875 Z-1.000000 I3.996220 J-8.833692
G03 X104.114870 Y46.384791 Z-1.000000 I5.541090 J-9.197028
G01 X104.114870 Y36.041237 Z-1.000000
G01 X101.783230 Y36.041237 Z-1.000000
G01 X101.783230 Y49.894655 Z-1.000000
G01 X104.114870 Y49.894655 Z-1.000000
G01 X104.114870 Y48.356764 Z-1.000000
G02 X105.255779 Y49.181726 Z-1.000000 I6.768064 J-8.158717
G02 X106.372090 Y49.770631 Z-1.000000 I4.522076 J-7.219435
G02 X107.564238 Y50.152914 Z-1.000000 I2.482396 J-5.691347
G02 X108.765750 Y50.279127 Z-1.000000 I1.201512 J-5.655919
G02 X110.831697 Y49.885952 Z-1.000000 I-0.000000 J-5.624370
G02 X112.188790 Y48.927272 Z-1.000000 I-1.289614 J-3.265439
G02 X113.010577 Y47.441889 Z-1.000000 I-3.047419 J-2.656000
G02 X113.367010 Y45.032936 Z-1.000000 I-7.962241 J-2.408953
G01 X113.367010 Y36.041237 Z-1.000000
G00 Z5.000000
M42 P24 S0
 
(End cutting path id: path7513)


(Start cutting path id: path7511)
(Change tool to Graffiti)
(Add G00 here to change sprayer if needed)
G00 Z5.000000
G00 X98.248558 Y42.726100
M42 P24 S170
 
G01 Z-1.000000 F100.0(Penetrate)
G01 X88.041429 Y42.726100 Z-1.000000 F400.000000
G03 X88.148848 Y41.469471 Z-1.000000 I7.403970 J-0.000000
G03 X88.425902 Y40.493678 Z-1.000000 I4.719840 J0.812862
G03 X88.898354 Y39.612669 Z-1.000000 I4.418415 J1.802245
G03 X89.480101 Y38.943385 Z-1.000000 I3.104893 J2.111327
G03 X90.173526 Y38.429785 Z-1.000000 I2.717125 J2.943555
G03 X91.005589 Y38.050417 Z-1.000000 I2.272710 J3.882548
G03 X91.911471 Y37.832331 Z-1.000000 I1.725156 J5.175457
G03 X92.965159 Y37.752760 Z-1.000000 I1.053688 J6.936763
G03 X94.353532 Y37.887880 Z-1.000000 I0.000000 J7.200388
G03 X95.805296 Y38.310866 Z-1.000000 I-1.631466 J8.302342
G03 X97.194021 Y38.962003 Z-1.000000 I-4.644262 J11.711615
G03 X97.851683 Y39.427077 Z-1.000000 I-1.663854 J3.050400
G01 X97.975706 Y39.427077 Z-1.000000
G01 X97.975706 Y36.884596 Z-1.000000
G02 X96.783716 Y36.428387 Z-1.000000 I-7.507129 J17.829412
G02 X95.569652 Y36.053639 Z-1.000000 I-6.258616 J18.121959
G02 X94.330219 Y35.805400 Z-1.000000 I-2.426645 J8.897707
G02 X92.989964 Y35.718776 Z-1.000000 I-1.340255 J10.324942
G02 X89.760553 Y36.261114 Z-1.000000 I-0.000000 J9.886102
G02 X87.607347 Y37.579127 Z-1.000000 I1.919432 J5.553559
G02 X86.236923 Y39.691041 Z-1.000000 I3.905639 J4.034965
G02 X85.672581 Y42.887331 Z-1.000000 I8.769307 J3.196290
G02 X86.203792 Y46.077484 Z-1.000000 I9.844738 J0.000000
G02 X87.520531 Y48.282350 Z-1.000000 I5.872782 J-2.011598
G02 X89.619145 Y49.731495 Z-1.000000 I4.344943 J-4.048083
G02 X92.407054 Y50.279127 Z-1.000000 I2.787909 J-6.822585
G02 X95.001930 Y49.803528 Z-1.000000 I-0.000000 J-7.316638
G02 X96.723070 Y48.642018 Z-1.000000 I-1.607515 J-4.237994
G02 X97.795432 Y46.826516 Z-1.000000 I-3.589221 J-3.344501
G02 X98.248558 Y43.991139 Z-1.000000 I-8.644443 J-2.835377
G01 X98.248558 Y42.726100 Z-1.000000
G00 Z5.000000
M42 P24 S0
 
(End cutting path id: path7511)


(Start cutting path id: path7511)
(Change tool to Graffiti)
(Add G00 here to change sprayer if needed)
G00 Z5.000000
G00 X95.978929 Y44.512038
M42 P24 S170
 
G01 Z-1.000000 F100.0(Penetrate)
G03 X95.696873 Y46.241903 Z-1.000000 I-5.681091 J-0.038379 F400.000000
G03 X95.048753 Y47.352174 Z-1.000000 I-2.904734 J-0.951333
G03 X94.008282 Y48.053138 Z-1.000000 I-1.925354 J-1.735195
G03 X92.283031 Y48.356764 Z-1.000000 I-1.725251 J-4.749764
G03 X90.538428 Y48.044920 Z-1.000000 I-0.000000 J-5.035993
G03 X89.294066 Y47.252955 Z-1.000000 I1.208460 J-3.272346
G03 X88.444690 Y46.029977 Z-1.000000 I2.967206 J-2.967209
G03 X88.041429 Y44.512038 Z-1.000000 I4.246322 J-1.940628
G01 X95.978929 Y44.512038 Z-1.000000
G00 Z5.000000
M42 P24 S0
 
(End cutting path id: path7511)


(Start cutting path id: path7509)
(Change tool to Graffiti)
(Add G00 here to change sprayer if needed)
G00 Z5.000000
G00 X84.457151 Y47.352174
M42 P24 S170
 
G01 Z-1.000000 F100.0(Penetrate)
G01 X84.333127 Y47.352174 Z-1.000000 F400.000000
G03 X83.809356 Y47.459124 Z-1.000000 I-1.915778 J-8.046226
G03 X83.316135 Y47.525807 Z-1.000000 I-1.206613 J-7.067297
G03 X82.831297 Y47.569858 Z-1.000000 I-0.839076 J-6.544969
G03 X82.162717 Y47.587817 Z-1.000000 I-0.668580 J-12.435942
G03 X81.111200 Y47.467367 Z-1.000000 I-0.000000 J-4.650054
G03 X80.079124 Y47.104125 Z-1.000000 I1.123730 J-4.840677
G03 X79.111996 Y46.573180 Z-1.000000 I3.697056 J-7.880570
G03 X78.144358 Y45.876293 Z-1.000000 I5.448692 J-8.585819
G01 X78.144358 Y36.041235 Z-1.000000
G01 X75.812717 Y36.041235 Z-1.000000
G01 X75.812717 Y49.894655 Z-1.000000
G01 X78.144358 Y49.894655 Z-1.000000
G01 X78.144358 Y47.848268 Z-1.000000
G02 X79.581630 Y48.884729 Z-1.000000 I10.647331 J-13.250007
G02 X80.587620 Y49.423366 Z-1.000000 I3.819368 J-5.924531
G02 X81.678673 Y49.778817 Z-1.000000 I2.297093 J-5.198682
G02 X82.758030 Y49.894655 Z-1.000000 I1.079357 J-4.970725
G02 X83.364875 Y49.881839 Z-1.000000 I0.000000 J-14.373665
G02 X83.638596 Y49.857445 Z-1.000000 I-0.124388 J-2.943623
G02 X83.910687 Y49.826539 Z-1.000000 I-0.552965 J-6.081324
G02 X84.457151 Y49.745824 Z-1.000000 I-3.357256 J-24.619905
G01 X84.457151 Y47.352174 Z-1.000000
G00 Z5.000000
M42 P24 S0
 
(End cutting path id: path7509)


(Start cutting path id: path7507)
(Change tool to Graffiti)
(Add G00 here to change sprayer if needed)
G00 Z5.000000
G00 X72.451683 Y49.894655
M42 P24 S170
 
G01 Z-1.000000 F100.0(Penetrate)
G01 X68.842601 Y36.041237 Z-1.000000 F400.000000
G01 X66.684593 Y36.041237 Z-1.000000
G01 X63.125120 Y46.719655 Z-1.000000
G01 X59.590452 Y36.041237 Z-1.000000
G01 X57.444847 Y36.041237 Z-1.000000
G01 X53.798558 Y49.894655 Z-1.000000
G01 X56.229417 Y49.894655 Z-1.000000
G01 X58.771898 Y39.166627 Z-1.000000
G01 X62.232152 Y49.894655 Z-1.000000
G01 X64.154515 Y49.894655 Z-1.000000
G01 X67.701585 Y39.166627 Z-1.000000
G01 X70.107640 Y49.894655 Z-1.000000
G01 X72.451683 Y49.894655 Z-1.000000
G00 Z5.000000
M42 P24 S0
 
(End cutting path id: path7507)


(Footer)
M5
G00 X0.0000 Y0.0000
M2
(Using default footer. To add your own footer create file "footer" in the output dir.)
(end)
%

However I am interested in F Value,Obviously I need more test info to report to you.

**Comment by wrenchonline** [comment]
I misunderstood the meaning of F （feed rate）, what I am doing is a writing machine. It is controlled by the steering gear M42, which has little to do with F（feed rate）.

**Comment by Paciente8159** [comment]
Ahh a custom machine...cool.
I see that you are using M42 to control the output of PWM0. You can in alternative use standart M3/M5 commands or eventually build a custom tool HAL module for your application. If you want to use the range os 0~255 instead of the range of 0~1000 that is configured by default you can change setting $30=255

µCNC also suports servo motors (PPM signal from 0.5ms~2.5ms) if you need to use that type of signal control.

Later tonight when I test your setup I'll also use your Gcode to see the behavior and give feedback.

About the board freeze, there are some strange issues with the atmega2560 MCU in terms of status query report speed.
Some programs like OpenCNCPilot default status pool rate is about 100ms. That means the program sends a `?` command every 100ms and some atmega2560 freezes at this rate. To cope with this and make the refresh rate responsive on the PC software it's possible to make this rate alot lower (for example send `?` command once every second) and enable an option on the config file:

```
// enables automatic status report sending
// this value sets the millisecond interval of the reports
// values bellow 100ms have no effect
#define STATUS_AUTOMATIC_REPORT_INTERVAL 0
```
 Setting `STATUS_AUTOMATIC_REPORT_INTERVAL` to 100 will make it send a status report automatically every 100ms

**Comment by Paciente8159** [comment]
I've tested the patch and all seems to be working fine.
I've also tested your settings and your Gcode file and all when well. Try to bump speeds to about `$110=6000` and `$111=6000` and accelerations to `$120=100` and `$121=100`

I'll merge this one now. Later I'll probably add the M919 command althoug it's possible to do it using the generic M920 command

**Comment by Paciente8159** [comment]
Just one more note on your gcode. You don't need that many decimal places in the coordinates.
With your config of 40steps/mm you Will get 0.025mm per step resolution. You should keep it to about 3 decimal places only (tipical for units in mm)
