### ISSUE TITLE
Can I send a compiled F103C8T6 HEX file? Email 459429772@qq.com

### ISSUE THREAD

**Issue by hankecnc** [Paciente8159/uCNC#35]
Hello, I am from China, I am a cnc enthusiast, my job is a machining center master, cnc is a hobby, I used this firmware from https://github.com/robomechs/6-AXIS-USBCNC- GRBL, I saw your source code today. I downloaded the source code to the linux system, installed arm-none gcc, and used the make command to compile, but after downloading, I connected the computer through the ch340g serial port module and sent $$ without any response, and then I tried to uncomment them separately in the boardmap_bluepill.h file//Setup COM pins (must match selected COM port)
//#define RX_BIT 10
//#define TX_BIT 9
//#define RX_PORT A
//#define TX_PORT A

And //#define COM_PORT 1
//#define TX_BIT 9
//#define TX_PORT A
//#define RX_BIT 10
//#define RX_PORT A
There is no response after compiling and downloading. I don’t know much about C++ and microcontrollers. Can you send me a HEX file of F103C8T6 to 459429772@qq.com, and tell me whether the communication method is serial or USB virtual serial

**Comment by Paciente8159** [comment]
I there. I just compiled the default version of µCNC (3 axis cartesian machine on bluepill with USB virtual COM port).
Try it and tell me if it works..

**Comment by hankecnc** [comment]
![QQ截图20210523220254](https://user-images.githubusercontent.com/69781416/119263720-c5450480-bc12-11eb-911a-9aa6b0808dc5.jpg)
 
I did not see any files available for download on this page,

I used this firmware earlier https://github.com/robomechs/6-AXIS-USBCNC-GRBL He works very well, I would like to try your firmware, but the process is not smooth,

**Comment by Paciente8159** [comment]
I sent it to your e-mail. I've also added the compiled hex in the [release v1.1.0](https://github.com/Paciente8159/uCNC/releases/tag/v1.1.0).
Thanks.

**Comment by hankecnc** [comment]
Thank you, I downloaded the uCNC-bluepill-usb.hex file of this page https://github.com/Paciente8159/uCNC/releases/tag/v1.1.0 to the blue f103c8t6 development board, connected via USB, the computer can The STM virtual serial port was recognized, but I did not get any reply when sending the $$ command through the serial port software, and then tried to connect the serial port PA9 and PA10 through the CH340 module, but there was no reply.
![QQ截图20210524091131](https://user-images.githubusercontent.com/69781416/119283806-b12ff000-bc70-11eb-84e0-d6d6c8dcb4e3.jpg)

**Comment by hankecnc** [comment]
Nothing happens when using other grbl-related software such as Candle

**Comment by Paciente8159** [comment]
This compilation uses the bluebill built in USB. Using and external serial cable doesn't work.
Also try this:
Short PINS B5 and B6 to ground before plugin in the USB cable. These pins are the hard reset and feed hold (negative logic). If left ungrounded the uCNC will be in failsafe mode and will not respond to any command.

**Comment by hankecnc** [comment]
Thank you very much for your patient guidance, I will follow your prompts
PINS B5 and B6 are grounded and have gotten a reply, thank you very much

**Comment by Paciente8159** [comment]
Your welcome. And thanks for trying out µCNC.
Any problem please report and I'll get to it ASAP.
I'll keep this issue open for a few more days in case you have any doubt.

**Comment by hankecnc** [comment]
I am willing to try new things.
What host computer do you use to operate uCNC?

Although uCNC can connect to the serial port software normally, it cannot use Candle2 https://github.com/Schildkroet/Candle2 The host computer communication on this page, click on the connection, no response, another laser drawing software is also, I guess whether it is a handshake protocol Has it changed? Because I am not good at programming, I can't solve this problem. Candle2 is excellent as a grbl host computer, and I don't want to give it up.
![QQ截图20210524203509](https://user-images.githubusercontent.com/69781416/119348525-8fb22100-bccf-11eb-9ecb-ac24942f3a0c.jpg)

**Comment by Paciente8159** [comment]
I'm using OpenCNCPilot. I like it alot and it has a very clean and simple interface.
I'll try Candle2 to see if I have any problems.
![image](https://user-images.githubusercontent.com/12116536/119349885-9a03f900-bc96-11eb-8db5-3512a0ec18c4.png)

**Comment by Paciente8159** [comment]
I've tested Candle2 and the original Candle. It seems to have been locked to use Grbl firmware. If I modify µCNC startup message to output:
`Grbl 1.1.1 ['$' for help]`
Candle2 and the original Candle both start communicating with µCNC.
To modify the startup message go to the grbl_interface.h file and modify the MSG_STARTUP_START from
`#define MSG_STARTUP_START "uCNC "`
to
`#define MSG_STARTUP_START "Grbl "`
Recompile the code and upload and it starts working.

**Comment by Paciente8159** [comment]
Since the problem was solved I'm closing the issue.
In a near future release an option to emulate Grbl startup message will be added to improve software compatibility.
