### ISSUE TITLE
[BUG] Not working servo

### ISSUE THREAD

**Issue by etet100** [Paciente8159/uCNC#355]
**Describe the bug**
M10 is not working?

**What is your hardware**
Describe your hardware:
Arduno UNO + CNC Shield v3

**What was the GCode running**
M10 P0 S0
M10 P0 S100
M10 P1 S0
M10 P1 S100

**Additional context**

It looks like this issue was introduced by https://github.com/Paciente8159/uCNC/commit/b10ff3189122dc024619622a2e3f4db172377cae

Maybe you just forgot to change SERVO0_UCNC_INTERNAL_PIN to 41?

**Comment by Paciente8159** [comment]
You are right. Thanks for the tip. SERVO0_UCNC_INTERNAL_PIN is a deprecated piece of code.
I will fix it right away.

**Comment by Paciente8159** [comment]
Thank you very much.
You were spot on.
