### ISSUE TITLE
[Enhancement] - Graphics Display - Change 'settings' menu order

### ISSUE THREAD

**Issue by mvackel** [Paciente8159/uCNC#514]
Module: Graphics Display

When using the graphics display is very common the firmware to interpret wrong the encoder direction and/or button press, sometimes interpreting one button click or one small rotation as two.
When configuring using menu Settings/Axis or Settings/Homing, after any adjust, a click in the return "X" in the upper right of the display, it's interpreted as two button clicks and this causes the "Settings/Load" menu item (first in "Settings") to be involuntary clicked, overwriting the last adjustment(s). 
It would be better if the menu items "Load settings" "Save settings" and "Reset settings" be positioned not in the beginning of the list. Or maybe, to change the order to place a less innocuous  item in the begin.
As a suggestion, the following order could solve the problem:
Settings->   - Homing ->
                    - Axis ->
                    -  IO config ->
                    -  Load settings
                    -  Save settings
                    -  Reset settings
                    - G64 
                    -  Arc tol
                    
Another option would be to place a confirmation after clicking "Load", "Save" or "Reset".

**Comment by Paciente8159** [comment]
Check [this branch](https://github.com/Paciente8159/uCNC/tree/514-enhancement-graphics-display-change-settings-menu-order) to get a modified version of the system menu with the settings re-organized
