### ISSUE TITLE
[FR] Support SCARA machines with  2 fixed motors

### ISSUE THREAD

**Issue by ademenev** [Paciente8159/uCNC#607]
SCARA kinematics implies that the arm motor is located on the forearm, and rotating only the forearm motor does not change the angle between the arm and the forearm. 

There is another way to implement a SCARA machine, pictured below. 

![1706825580043](https://github.com/Paciente8159/uCNC/assets/2399220/715927d2-7df7-4fa8-8f36-1d92ddea01a6)

In this type of machine, keeping constant angle between the  arm and the forearm requires rotating both motors. Forward and inverse kinematics is not much more complex, but is different. 

I intend to implement this time of kinematics, the only question is: what would be the best name for it?

**Comment by Paciente8159** [comment]
Awesome.
If it's the first of it's kind you can give any name you want. If not it would be preferable to follow existing naming conventions (like in GCode implementations) (using naming conventions used in other firmware like Marlin or LinuxCNC).
Let me know if any question arises.

**Comment by ademenev** [comment]
It is not new, the idea is pretty simple and I guess it has been implemented independently by multiple people. In Marlin, it is known as MP SCARA (mostly printed SCARA). 

Probably, it would be easier to make that not a separate kinematics, but just an additional config option

**Comment by Paciente8159** [comment]
> Probably, it would be easier to make that not a separate kinematics, but just an additional config option

If that can be done over the existing SCARA kinematic then ok.
I'm not against having a completely separate kinematic if it improves readability or for customization/maintenance reasons.

**Comment by Paciente8159** [comment]
Implemented with #645
