### ISSUE TITLE
Ask if it has the function of PCB cutting proximity switch to test the flatness of the mesh bed

### ISSUE THREAD

**Issue by wrench1997** [Paciente8159/uCNC#672]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the feature is:
custom harware

**Describe the solution you'd like**
Ask if it has the function of PCB cutting proximity switch to test the flatness of the mesh bed.Proximity switch-like leveling function.

**Describe your target machine hardware**
 diy cnn machine have  cutting pCB

**Additional context**
![222](https://github.com/Paciente8159/uCNC/assets/162891238/88459207-d37c-43de-be64-3a736d9adcbd)

**Comment by Paciente8159** [comment]
I'm not sure if I understood correctly. You need a height map feature?
The height map (bed leveling similar to 3d printing) feature is implemented.
Just need to enable it in [the configuration](https://github.com/Paciente8159/uCNC/blob/17a08e90815bf1ee58a6e25c4af573314591c0d2/uCNC/cnc_config.h#L407)

**Comment by wrench1997** [comment]
> I'm not sure if I understood correctly. You need a height map feature? The height map (bed leveling similar to 3d printing) feature is implemented. Just need to enable it in [the configuration](https://github.com/Paciente8159/uCNC/blob/17a08e90815bf1ee58a6e25c4af573314591c0d2/uCNC/cnc_config.h#L407)
Yes, that's right! There are instructions in the code, but it’s not clear how to select the xy axis  boundary length of the detection range.
