### ISSUE TITLE
Module event listeners with locks issue

### ISSUE THREAD

**Issue by patryk3211** [Paciente8159/uCNC#727]
https://github.com/Paciente8159/uCNC/blob/3f1a64e53efe606159199383fd938d7078713740/uCNC/src/module.h#L68

`CLEARFLAG` macro cannot be used here since it is an assigning operation. This has to be replaced with
```c
lock_flags & ~(LISTENER_RUNNING_LOCK)
```

**Comment by Paciente8159** [comment]
Once again thanks for spotting this.
