### ISSUE TITLE
KINEMATIC_DELTE and KINEMATIC_LINEAR_DELTA seem to be inversed

### ISSUE THREAD

**Issue by bschwand** [Paciente8159/uCNC#795]
I was studying the uCNC code and noticed in cnc_config.h delta defines at line 155 and 160 are inversed at least according to the documentation description here
https://github.com/Paciente8159/uCNC/blob/master/uCNC/src/hal/kinematics/README.md#linear-delta

I understand rotary delta has a jointed arm (biceps+forearm, which BTW is a bit of a misnomer, it should be arm and forearm but I see the logic) and a rotary actuator (5 extra parameters), whereas a linear delta just has an arm and linear actuator (2 extra parameters.

https://github.com/Paciente8159/uCNC/blob/bf610b9f171361fda6862f1432d09e3fc49f101d/uCNC/cnc_config.h#L155

so I think L155 should be 
#if defined(KINEMATIC_LINEAR_DELTA)

and L 160
#if defined(KINEMATIC_DELTA)

**Comment by Paciente8159** [comment]
Yup you are correct. Thanks for reporting this.
